course/urls.py
from django.urls import path
from . import views
# from .views import CourseDetailView
# from .views import AddWeekView, UpdateWeekView

app_name = 'course'

urlpatterns = [
    path('add-week/<int:pk>', views.add_week , name='add-week'),
    path('update-week/<int:pk>', views.update_week, name='update-week'),
    path('list/', views.course, name='listcourse'),
    path('search/', views.search, name='search'),
    path('enroll/<int:id_course>/', views.enroll, name='enroll'),
    path('success/', views.success, name='success'),
    path('unenroll/<int:id_course>/', views.unenroll, name='unenroll'),
    path('detail/<int:id_enroll>/', views.coursepage, name='course_page')
]  

sekele/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('helloworld.urls')),
    path('announcement/', include('announcement.urls')),
    path('course/', include('course.urls')),
    path('account/', include('account.urls')),
    path('search/', include('searchbooks.urls')),
]

course/models.py
from django.db import models
from django.urls import reverse
from sekele.settings import AUTH_USER_MODEL as User
import datetime

# Create your models here.
# class Student(models.Model):
#     name = models.CharField(max_length=256)

#     def __str__(self):
#         return self.name

class Course(models.Model):
    name = models.CharField(max_length=256)
    fullname = models.CharField(max_length=256, default="Algorithm")
    syllabus = models.CharField(max_length=256, default='https://docs.google.com/document/d/1ylU3ZOxiG38ORD9em_8GTQ6ZacgFwQ96KQOTbpygZTI/edit?usp=sharing')
    description = models.TextField(default='no desc')
    member = models.ManyToManyField(User, through='Enrollment')
    image = models.CharField(max_length=256, default='coding.png')

    def __str__(self):
        return self.name

class Week(models.Model):
    topic = models.TextField(default='Read the syllabus')
    google_meet_link = models.CharField(max_length=256, default='https://docs.google.com/document/d/1ylU3ZOxiG38ORD9em_8GTQ6ZacgFwQ96KQOTbpygZTI/edit?usp=sharing')
    homework_drive  = models.CharField(max_length=256, default='https://docs.google.com/document/d/1ylU3ZOxiG38ORD9em_8GTQ6ZacgFwQ96KQOTbpygZTI/edit?usp=sharing')
    quiz_forms = models.CharField(max_length=256, default='https://docs.google.com/document/d/1ylU3ZOxiG38ORD9em_8GTQ6ZacgFwQ96KQOTbpygZTI/edit?usp=sharing')
    topic_sheets = models.CharField(max_length=256, default='https://docs.google.com/document/d/1ylU3ZOxiG38ORD9em_8GTQ6ZacgFwQ96KQOTbpygZTI/edit?usp=sharing')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

class Enrollment(models.Model):
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrollment = models.DateField(default = datetime.date.today)

    class Meta:
        unique_together = [['member','course']]

course/forms.py
from django import forms
from .models import Week

class FormAddWeek(forms.ModelForm):
    class Meta:
        model = Week
        fields = {
            'topic',
            'google_meet_link',
            'homework_drive',
            'quiz_forms',
            'topic_sheets',
        }
        widgets = {
            'google_meet_link' : forms.TextInput(attrs={'class': 'form-control'}),
            'homework_drive' : forms.TextInput(attrs={'class': 'form-control'}),
            'quiz_forms' : forms.TextInput(attrs={'class': 'form-control'}),
            'topic_sheets' : forms.TextInput(attrs={'class': 'form-control'}),
            'topic' : forms.TextInput(attrs={'class': 'form-control'}),
        }

course/views.py
from django.forms.forms import Form
from course.forms import FormAddWeek
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Course, Week
from django.http import HttpResponseRedirect, JsonResponse
from .forms import FormAddWeek
from .models import Course, Week, Enrollment
from django.db.models import Q
from account.models import Account
from django.contrib.auth.models import Group
from account.decorators import allowed_user, unauthenticated_user
from django.contrib.auth.decorators import login_required
import json

# Create your views here.
@login_required(login_url='/account/login/')
@allowed_user(allowed_roles=['lecturer'])
def add_week(request, pk):
    course = Course.objects.get(pk=pk)
    form = FormAddWeek(request.POST or None)
    User = request.user
    Role = User.groups.values_list('name',flat = True)
    Roles = list(Role)
    enroll = Enrollment.objects.get(member=User, course=course)
    if (request.method == 'GET'):
        response = {
            'form' : form,
            'User' : User,
            'Roles':Roles,
        }
        return render(request, 'course/add-week.html', response)
    elif (form.is_valid() and request.method == 'POST'):
        topic               = form.cleaned_data['topic']
        google_meet_link    = form.cleaned_data['google_meet_link']
        homework_drive      = form.cleaned_data['homework_drive']
        quiz_forms          = form.cleaned_data['quiz_forms']
        topic_sheets        = form.cleaned_data['topic_sheets']
        participant         = Week.objects.create(topic = topic, google_meet_link = google_meet_link, homework_drive = homework_drive, quiz_forms = quiz_forms, topic_sheets = topic_sheets, course = course)
        participant.save()
        return HttpResponseRedirect('/course/detail/' + str(enroll.pk) + '/') #tambahin pk course

@login_required(login_url='/account/login/')
@allowed_user(allowed_roles=['lecturer'])
def update_week(request, pk):
    week = Week.objects.get(pk = pk)
    course = week.course
    a = course.pk
    User = request.user
    Role = User.groups.values_list('name',flat = True)
    Roles = list(Role)
    enroll = Enrollment.objects.get(member=User, course=course)
    data = {
        'topic'             : week.topic,
        'google_meet_link'  : week.google_meet_link,
        'homework_drive'    : week.homework_drive,
        'quiz_forms'        : week.quiz_forms,
        'topic_sheets'      : week.topic_sheets,
    }

    form = FormAddWeek(request.POST or None, initial=data, instance=week)
    context = {
        'form' : form,
        'User' : User,
        'Roles':Roles,
    }
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/course/detail/' + str(enroll.pk) + '/' ) #tambahin pk course
    
    return render(request, 'course/add-week.html', context) 

@login_required(login_url='/account/login/')
def course(request):
    course = Course.objects.all()
    User = request.user
    context={
        'course':course,
        'User' : User,
    }

    return render(request, 'course/list-matkul.html', context)

@login_required(login_url='/account/login/')
def enroll(request, id_course):
    User = request.user
    course_obj = Course.objects.get(id=id_course)
    member_obj = User

    course_obj.member.add(member_obj)    
    course_obj.save()

    return redirect('/course/success/')

@login_required(login_url='/account/login/')
def unenroll(request, id_course):

    course_obj = Course.objects.get(id=id_course)
    member_obj = request.user

    Enrollment.objects.filter(member=member_obj, course=course_obj).delete()

    return redirect('/dashboard')

@login_required(login_url='/account/login/')
def success(request):
    User = request.user
    context={
        'User' : User,
    }
    return render(request, 'course/success.html', context)

@login_required(login_url='/account/login/')
def coursepage(request, id_enroll):
    User = request.user
    list_course = Enrollment.objects.filter(member=User)
    enroll_obj = Enrollment.objects.get(id=id_enroll)
    course_target = Course.objects.get(name=enroll_obj.course)
    week_obj = Week.objects.filter(course=course_target)
    Role = User.groups.values_list('name',flat = True)
    Roles = list(Role)
    # lecturer = Enrollment.objects.filter(member=Group.objects.get(name='lecturer'), course=course_target)
    lecturer = []
    # for i in Account.objects.all():
    #     if 'lecturer' in list.groups.values_list('name',flat = True) and :
    #         lecturer.append(i)
    for i in Enrollment.objects.all():
        if 'lecturer' in i.member.groups.values_list('name',flat = True) and i.course == course_target:
            lecturer.append(i)
    context={
        'listCourse':list_course,
        'title':'Enrolled Course',
        'course_obj':course_target,
        'week_obj':week_obj,
        'User' : User,
        'Roles':Roles,
        'lecturer':lecturer
    }

    return render(request, "course/course-detail.html", context)

@login_required(login_url='/account/login/')
def search(request):
    searchCourse = request.GET['q']
    objCourse = Course.objects.filter(name__icontains=searchCourse)
    data = objCourse.values()
    return JsonResponse(list(data), safe=False)

course/templates/course/add-week.html
{% extends "base.html" %}
{% block title%}
SEKELE | Week Form
{% endblock %}

{% block content %}
<div class="banner text-center" style="width: 100%; height:100px; background-color:#8075FF;">
    <div style="height:15px;"></div>
    <h1 class="title align-middle" style="font-size:60px; font-family:'Poppins'; font-weight:bolder; color:#FBFBFB; vertical-align:middle;">Week Form</h1>
</div>
<br><br>
<div class="text-center col-12">
    <div class="form col rounded" style="background-color: #6320EE;color:#FBFBFB; margin:auto; max-width:420px;">
        <br>
        Please include the whole link with "https://"
        <br><br>
        <form action="" method='POST'> {% csrf_token %}
            {{ form.as_p}}
            <input class="btn btn-light"  type='submit' value='Submit' />
        </form>
        <br>
    </div>
</div>

{% endblock %}

course/templates/course/course-detail.html
{% extends 'base.html' %}

{% block title %}
SEKELE | Mata Kuliah
{% endblock %}

{% block css %}

    <style>
        * {
            margin: 0%;
            padding: 0%;
            font-family: 'Poppins';
            text-decoration: none;
        }

        h1 {
            font-family: 'Poppins';
            font-style: normal;
            font-weight: bold;
            font-size: 28px;
            line-height: 40px;
            align-items: center;
            text-align: center;
            color: #ffffff;
            margin: 5% 0px;
        }

        .container {
            margin-top: 3%;
        }

        .col-sm {
            margin: 2% 3%;
        }

        .col-sm-3 {
            margin: 2% 3%;
            background: #8075FF;
            border-radius: 15px;
        }

        .col-sm-4 {
            width: 100%;
        }

        .card {
            height: 80px;
            width: 98%;
            background: #6320EE;
            border-radius: 15px;
            margin: 5% 0px;
            padding: 3%;
            margin-right: auto;
            margin-left: auto;
        }

        .fa-user {
            color: white;
            font-size: 50px;
            margin: 2% 3%;
        }

        h2 {
            font-family: Rubik;
            font-style: normal;
            font-weight: bold;
            font-size: 17px;
            align-items: center;
            text-align: center;
            color: #FBFBFB;
        }

        h3 {
            font-family: 'Poppins';
            font-style: normal;
            font-weight: bold;
            font-size: 36px;
            line-height: 40px;
            align-items: center;
            text-align: center;
            color: #ffffff;
            margin: 2% 0px;
        }

        h4 {
            font-family: Poppins;
            font-style: normal;
            font-weight: bold;
            font-size: 24px;
            line-height: 40px;
            color: #000000;
            margin: 2% 0px;
        }

        .header-course {
            width: 100%;
            background-color: #8075FF;
            border-radius: 15px;
            padding: 1%;
        }

        p{
            margin-left: 2%;
        }

        .week-card {
            width: 100%;
            border-radius: 15px;
            margin: 5% 0px;
            padding: 3%;
            background: #FBFBFB;
            box-shadow: -10px -10px 0px #8075FF;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h1>{{title}}</h1>
                {% for i in listCourse %}
                <a href="/course/detail/{{i.id}}/" style="text-decoration: none;">
                    <div class="card row d-flex justify-content-center" style="background-image: url('/static/images/{{i.course.image}}'); background-color: rgba(0, 0, 0, 0.3); background-blend-mode: darken;";>
                        <h2>{{i.course}}</h2>
                    </div>  
                    {% endfor %}
                </a>
                <a href="/course/list/" class="btn btn-primary d-flex justify-content-center" style="background-color: white; color:#6320EE; margin-bottom:5%">Add Course &nbsp;<i class="fa fa-plus"></i></a>
            </div>
            <div class="col-sm">
                <div class="header-course">
                    <h3>Course Information</h3>
                    <p style="color: #222222;"><b>Course :</b> {{course_obj.name}}   </p>
                    <p style="color:#222222;"><b>Lecturer :</b> {% for i in lecturer %}{{i.member.username}},{% endfor %}</p> 
                    <a style="color: #222222;" target="_blank"  href="{{course_obj.syllabus}}"><p><b>Syllabus Document</b></p></a>
                    <a style="color: #222222;"  href="{% url 'course:unenroll' course_obj.id %}"><p>Unenroll from this course</p></a>
                </div>
                {% for i in week_obj %}
                <div class="week-card">
                    <h4>Week {{forloop.counter}}</h4>
                    Topic: {{i.topic}}
                    {% if 'lecturer' in Roles %}
                    <a href="{% url 'course:update-week' i.pk %}">Edit week</a> <!-- dosen doang --> 
                    {% endif %}
                    <br><p></p>
                    <a style="color: black;" target="_blank"  href="{{i.google_meet_link}}">Synchronous class</a> <br>
                    <a style="color: black;" target="_blank"  href="{{i.homework_drive}}">Weekly homework</a> <br>
                    <a style="color: black;" target="_blank"  href="{{i.quiz_forms}}">Weekly Quiz</a> <br>
                    <a style="color: black;" target="_blank"  href="{{i.topic_sheets}}">Material</a> 
                </div>  
                {% endfor %}
                {% if 'lecturer' in Roles %}
                <a href="{% url 'course:add-week' course_obj.pk %}" class="btn btn-primary" style="background-color: #6320EE; margin-top:5%;">Add Week</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock  %}

course/templates/course/list-matkul.html
{% extends 'base.html' %}

{% block title %}
SEKELE - Course List
{% endblock %}

{% block css %}

<style>
    * {
        margin: 0%;
        padding: 0%;
        font-family: poppins;
    }

    a {
        text-decoration: none;
    }

    h1 {
        margin: 0.5% 0px;
        font-family: Poppins;
        font-weight: bold;
        font-size: 200%;
        color: #6320EE;
        text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    h3 {
        text-align: center;
    }

    .container-fluid {
        margin-top: 4%;
    }

    .container {
        margin-top: 10px;
    }

    /*.row{
            margin: 2% 1%;
        }*/

    #purplebg {
        background-color: #6320EE;
        color: white;
    }

    #purplebg:hover {
        background-color: #6338BC;
    }

    #whitebg {
        border-color: #6320EE;
        background-color: white;
        color: #6320EE;
    }

    #whitebg:hover {
        color: #6320EE;
        border-color: white;
    }

    .card {
        margin: 5%;
    }

    img.card-img-top {
        width: 100%;
        height: 15vw;
    }

    .btnenroll {
        display: flex;
        justify-content: center;
    }

    .search-box {
        margin: 0.5% 0px;
    }

    input[type='text'] {
        float: right;
        width: 50%;
    }

    p {
        text-align: center;
    }
</style>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="d-flex text-white">
        <div class="p-2 flex-fill">
            {% if object_list != null %}
            <h1>Hasil Pencarian</h1><a href="/course/list/">kembali</a>
            {% else %}
            <h1>Add your Course Here</h1>
            {% endif %}
        </div>
        <div class="p-2 flex-fill search-box">
            <input type="text" class="form-control" name="q" id="keyword" aria-describedby="emailHelp"
                placeholder="Search your course here" autocomplete="off">
        </div>
    </div>
</div>
<div class="container">
    <div id="result"
        class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 d-flex justify-content-center"
        style="margin: 2% 1%;">
    </div>
</div>

<script type="text/javascript">

    const vara = $("#keyword").val();

    $("#keyword").ready(function () {
        search_course($("#keyword").val());
    })

    $("#keyword").keyup(function () {
        search_course($("#keyword").val());
    })

    $("#keyword").keypress(function () {
        search_course($("#keyword").val());
    })

    console.log(vara);

    function search_course(input) {
        $.ajax({

            url: '/course/search/?q=' + input,

            success: function (data) {
                //assign items into array_items
                var array_items = data;
                $("#result").empty();

                //iterate every items in array_items
                for (i = 0; array_items.length; i++) {
                    //getting the title of the books
                    var index = array_items[i];

                    var course = index.name;
                    var image = "/static/images/" + index.image;
                    var description = index.description;
                    var link_enroll = "/course/enroll/" + index.id;
                    var class_btn = "btn btn-primary";
                    var dflex = "d-flex justify-content-center"

                    $("#result").append(
                        "<div class=" + "row " + "style=" + "margin:2% 1%;" + ">" +
                        "<div class=card>" +
                        "<img " + "class=" + "card-img-top " + "src=" + image + ">" +
                        "<div class=" + "card-body" + ">" +
                        "<h3 class=" + "card-title" + ">" + "<b>" + course + "</b></h3>" +
                        "<p class=" + "card-text" + ">" + description + "</p>" +
                        "<div class=" + "btnenroll" + ">" +
                        "<a href=" + link_enroll + " id=purplebg " + "class=" + "btn" + ">" + "Enroll" + "</a > " +
                        "</div>" +
                        "</div>" +
                        "</div>" +
                        "</div>"
                    );
                }
            }
        });
    }
</script>

{% endblock  %}

course/templates/course/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Success Enroll</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <style>
        * {
            margin: 0%;
            padding: 0%;
            font-family: poppins;
        }

        body {
            background-image: url('{% static "images/background.jpg"%}');
            background-attachment: fixed;
            height: 100vh;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .btn {
            background-color: #6320ee;
        }

        .btn:hover {
            background-color: #6338bc;
        }
    </style>

</head>

<body>
    <div class="container d-flex justify-content-center">
        <h1>Success Enroll</h1> &nbsp;&nbsp;
        <div class="d-flex justify-content-center">
            <a href="/course/list/" class="btn btn-primary">Kembali</a>
        </div>
    </div>
</body>

</html>