account/urls.py
from django.urls import path
from account.views import register_view, login_view, logout_view, profile_view, search_view, search_page_view


app_name = 'account'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('search/', search_page_view, name='search'),
    path('data/', search_view, name='data')
]

announcement/urls.py
from django.urls import path
from . import views

app_name = 'announcement'

urlpatterns = [
    path('<int:idAn>/view',views.AnnView, name='viewAn'),
    path('add', views.AnnAdd, name='addAn'),
    path('<int:idAn>/edit', views.AnnEdit, name='editAn'),
    path('<int:idAn>/delete', views.AnnDelete, name='deleteAn'),
    path('all',views.AnnAll, name='allAn'),
    path('search/',views.AnnSearch, name='searchAn'),
]

course/urls.py
from django.urls import path
from . import views
# from .views import CourseDetailView
# from .views import AddWeekView, UpdateWeekView

app_name = 'course'

urlpatterns = [
    path('add-week/<int:pk>', views.add_week , name='add-week'),
    path('update-week/<int:pk>', views.update_week, name='update-week'),
    path('list/', views.course, name='listcourse'),
    path('search/', views.search, name='search'),
    path('enroll/<int:id_course>/', views.enroll, name='enroll'),
    path('success/', views.success, name='success'),
    path('unenroll/<int:id_course>/', views.unenroll, name='unenroll'),
    path('detail/<int:id_enroll>/', views.coursepage, name='course_page')
]  

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard',views.dashView, name='viewDash'),
]

sekele/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('helloworld.urls')),
    path('announcement/', include('announcement.urls')),
    path('course/', include('course.urls')),
    path('account/', include('account.urls')),
    path('search/', include('searchbooks.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from announcement.models import AnnouncementModel
from course.models import Enrollment
from account.decorators import allowed_user, unauthenticated_user
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/account/login/')
def dashView(request):
    boolAnn = False
    Ann = AnnouncementModel.objects.all()
    if len(Ann) > 0:
        boolAnn = True;
    User = request.user
    Role = User.groups.values_list('name',flat = True)
    Roles = list(Role)
    boolCourse = False;
    list_course = Enrollment.objects.filter(member=User)
    if len(list_course) > 0:
        boolCourse = True;
    context = {
        'boolAnn':boolAnn,
        'Anns':Ann,
        'Roles':Roles,
        'User':User,
        'boolCourse':boolCourse,
        'Enrolled':list_course,
    }
    return render(request,'dashboard.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{% static 'images/logo.png' %}" type="image/icon type">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <title>{% block title %}{% endblock %}</title>
  <style>
    html {
      height: 100%;
      box-sizing: border-box;
    }

    *,
    *:before,
    *:after {
      box-sizing: inherit;
    }

    body {
      position: relative;
      margin: 0;
      padding-bottom: 6rem;
      min-height: 100%;
      font-family: 'Poppins';
    }

    body {
      background-image: url("{% static 'images/background.jpg' %}");
      background-size: cover;
      background-position: center center;
      background-repeat: no-repeat;
      background-attachment: fixed;
    }

    .footer {
      position: absolute;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 1rem;
      background-color: #8075FF;
      color: #FBFBFB;
      font-weight: bold;
      height: 120px;
    }

    navbar {
      background-color: #6320EE;
      color: #FBFBFB;

    }
  </style>

  {% block css %}
  {% endblock %}
</head>

<body>

  <nav class="navbar navbar-expand fixed-top navbar-dark"
    style="background-color:#6320EE;font-family: Poppins; font-weight:900">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a href="{% url 'dashboard:viewDash' %}"><img src="{% static 'images/logo.png' %}" alt="logo"
          style="width: 70px; margin-right:10px;"></a>
      <a style="font-size: 30px; font-weight:900;" class="navbar-brand" href="{% url 'dashboard:viewDash' %}">SEKELE</a>
      <!-- front page -->
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      </ul>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color: black;" href="#" id="navbarDropdownMenuLink" role="button"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span style="color: #FBFBFB;">{{User.username}}</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/search/">Books</a> <!-- user -->
          <a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a> <!-- user -->
          <a class="dropdown-item" href="{% url 'course:listcourse' %}">Courses</a> <!-- user -->
          <a class="dropdown-item" href="{% url 'dashboard:viewDash' %}">Dashboard</a> <!-- user -->
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account:logout' %}">Log out</a> <!-- user -->
        </div>
      </div class>
      <img src="{% static 'images/user.png' %}" alt="" style="width: 70px;">
    </div>
  </nav>
  <!-- <img src="{% static 'images/background.jpg' %}" alt="" style="height:100vh;"> -->


  <br><br><br><br>
  {% block content%}
  {% endblock %}
  <br><br><br><br><br>
  <!-- <br><br><br><br> -->





  <!-- necessary for the bootstrap navbar -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <footer class="footer">
    <div style="height: 25px;"></div>
    <div class="row">
      <div class="col-sm-6">
        university@gmail.com
      </div>
      <div class="col-sm-6">
        <div class="row float-right">
          <!-- <div class="col-1">A</div>
          <div class="col-1">B</div>
          <div class="col-1">C</div>
          <div class="col-1">D</div> -->
          <a class="col" href="https://www.youtube.com/user/numberphile" target="_blank"><img
              src="{% static 'images/youtube.png' %}" alt="A" style="height: 32px;"></a>
          <a class="col" href="https://www.youtube.com/user/numberphile" target="_blank"><img
              src="{% static 'images/twitter.png' %}" alt="A" style="height: 32px;"></a>
          <a class="col" href="https://www.youtube.com/user/numberphile" target="_blank"><img
              src="{% static 'images/facebook.png' %}" alt="A" style="height: 32px;"></a>
          <a class="col" href="https://www.youtube.com/user/numberphile" target="_blank"><img
              src="{% static 'images/ig.png' %}" alt="A" style="height: 32px;"></a>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block title %}SEKELE - Dashboard{% endblock %}

{% block css %}
<style>
.col-sm-3 {
    margin: 2% 3%;
    background: #8075FF;
    border-radius: 15px;
}
.card {
    height: 80px;
    width: 98%;
    background: #6320EE;
    border-radius: 15px;
    margin: 5% 0px;
    padding: 3%;
    margin-right: auto;
    margin-left: auto;
}
</style>
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-1"></div>
    <div class="col-3">
        <div class="container">
            <div class="container" style="background-color:#8075FF;border-style: solid;border-radius:25px;border-color:#6320EE">
                
                {% if 'student' in Roles %}
                <div class="text-center">
                    <h1>{{title}}</h1>
                    <a href="#" style="text-decoration: none; color:#FBFBFB;">
                        <div class="card row d-flex justify-content-center" style="background-color:#FBFBFB;; background-color: rgba(0, 0, 0, 0.3); background-blend-mode: darken;";>
                            <h2>TO-DO LIST</h2>
                        </div>
                    </a>
                </div>
                <br>
                {% endif %}
                {% if boolCourse %}
                    {% for i in Enrolled %}
                        <div class="text-center">
                            <h1>{{title}}</h1>
                            <a href="/course/detail/{{i.id}}/" style="text-decoration: none; color:#FBFBFB;">
                                <div class="card row d-flex justify-content-center" style="background-image: url('/static/images/{{i.course.image}}'); background-color: rgba(0, 0, 0, 0.3); background-blend-mode: darken;";>
                                    <h2>{{i.course}}</h2>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                
                {% else %}
                    <div class="text-center">
                        <h1>{{title}}</h1>
                        <a href="/course/list/" style="text-decoration: none; color:#FBFBFB;">
                            <div class="card row d-flex justify-content-center" style="background-color:#FBFBFB; background-color: rgba(0, 0, 0, 0.3); background-blend-mode: darken;";>
                                <h2><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Add Course</h2>
                            </div>
                        </a>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
    <div class="col-7">
        <div class="container">
            {% if 'lecturer' in Roles %}
                <a href="{% url 'announcement:addAn' %}" class="btn btn-primary" style="background-color:#FBFBFB;border-color:#FBFBFB; color:black;"><b>Add Announcement</b></a>
                &nbsp;&nbsp;&nbsp;
                <a href="{% url 'announcement:allAn' %}" class="btn btn-primary" style="background-color:#FBFBFB;border-color:#FBFBFB; color:black;"><b>Search Announcement</b></a>
            {% endif %}
            <br><br><br>
            {% for Ann in Anns reversed %}
            <div class="container" style="border-radius:25px;box-shadow: -10px -10px 0px #8075FF; background-color:#FBFBFB;">
                <h1>{{Ann.judulAn|title}}</h1>
                <p>{{Ann.publisherAn}} | <b>Posted on</b> {{Ann.postedAn}}, <b>last edited on</b> {{Ann.lastEditAn}}</p>
                <p>{{Ann.isiAn|truncatewords:50}}
                    <a href="{% url 'announcement:viewAn' idAn=Ann.id %}"><b>Read More</b></a>
                </p>
                
                <div class="row" style="margin: auto;">
                    {% if Ann.publisherAn == User %}
                    <a href="{% url 'announcement:editAn' idAn=Ann.id %}" class="btn btn-primary" style="background-color:#6320EE;border-color:#6320EE;">Edit</a>
                    <p>&nbsp;&nbsp;&nbsp;</p>
                    <a href="{% url 'announcement:deleteAn' idAn=Ann.id %}" class="btn btn-primary" style="background-color:#6320EE;border-color:#6320EE;">Delete</a>
                    <p>&nbsp;&nbsp;&nbsp;</p>
                    {% endif %}
                    <a href="{% url 'announcement:viewAn' idAn=Ann.id %}" class="btn btn-primary" style="background-color:#6320EE;border-color:#6320EE;">View</a>
                </div>
                <br>
            </div>
            &nbsp;&nbsp;
            {% endfor %}
        </div>
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SEKELE</title>
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/icon type">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" 
    rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Rubik' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

    <style>
        *{
            margin: 0%;
            padding: 0%;
            font-family: poppins;
        }

        body{
            background-image: url('{% static "images/background.jpg"%}');
            background-attachment: fixed;
            height: 100vh;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container{
            height: 80vh;
            margin-top: 5%;
        }

        h1{
            font-family: Poppins;
            font-style: normal;
            font-weight: 600;
            font-size: 80px;
            line-height: 136px;
            /* identical to box height */
            display: flex;
            align-items: center;
            letter-spacing: 0.05em;
            color: #211A1D;
            margin-top: 10%;
        }

        p{
            font-family: Rubik;
            font-style: normal;
            font-weight: 500;
            font-size: 18px;
            line-height: 151.1%;
            /* or 27px */

            display: flex;
            align-items: center;
            letter-spacing: 0.05em;

            color: #211A1D;
        }

        .btn{
            width: 140px;
            height: auto;
            background-color: #6320EE;
            font-family: Poppins;
            font-style: normal;
            font-weight: bold;
            font-size: 13px;
            line-height: 27px;
            letter-spacing: 0.05em;
            color: #FBFBFB;
            margin-right: 10px;
        }

        #purplebg:hover{
            background-color: #6338BC;
        }

        #whitebg{
            border-color: #6320EE;
            background-color: white;
            color: #6320EE;
        }   

        #whitebg:hover{
            border-color: white ;
        }

    </style>

</head>
<body>
    <div class="container">
        <h1>Welcome</h1>
        <p>Welcome to our website, an education <br>  website platform for during pandemic <br> Covid-19</p>
        <a href=" {% url 'account:register' %}" id="purplebg" class="btn btn-primary"> Sign Up</a>
        <a href="{% url 'account:login' %}" id="whitebg" class="btn btn-outline-primary" id="whitebg">Login</a>
    </div>
</body>
</html>